export const PAGE_TITLES: Record<string, string> = {
  '/': 'BioVision — Spatio-Temporal & Physiological Deepfake Detection',
  '/analysis': 'Analyze Video — BioVision',
  '/results': 'Analysis Results — BioVision',
  '/architecture': 'Architecture — BioVision',
  '/model': 'Architecture — BioVision',
  '/evaluation': 'Experimental Evaluation — BioVision',
  '/metrics': 'Experimental Evaluation — BioVision',
  '/how-it-works': 'How It Works & Methodology — BioVision',
  '/learn': 'How It Works & Methodology — BioVision',
  '/history': 'Analysis History — BioVision',
  '/about': 'About BioVision — Research Rationale',
  '/dashboard': 'Dashboard — BioVision',
  '/contact': 'Contact — BioVision',
  '/settings': 'Settings — BioVision',
  '/login': 'Sign In — BioVision',
  '/register': 'Create Account — BioVision',
}
