export const PAGE_TITLES: Record<string, string> = {
  '/': 'BioVision',
  '/analysis': 'Analyze — BioVision',
  '/results': 'Results — BioVision',
  '/architecture': 'Architecture — BioVision',
  '/model': 'Architecture — BioVision',
  '/evaluation': 'Evaluation — BioVision',
  '/metrics': 'Metrics — BioVision',
  '/how-it-works': 'How It Works — BioVision',
  '/learn': 'How It Works — BioVision',
  '/history': 'History — BioVision',
  '/about': 'About — BioVision',
  '/dashboard': 'Dashboard — BioVision',
  '/contact': 'Contact — BioVision',
  '/settings': 'Settings — BioVision',
  '/login': 'Sign In — BioVision',
  '/register': 'Create Account — BioVision',
}
